#!/bin/bash

# Quick Setup Verification Script for Google Sign-In
echo "=== GOOGLE SIGN-IN SETUP VERIFICATION ==="
echo ""

echo "✅ Your Configuration:"
echo "   Project ID: acespire-485012"
echo "   Web Client ID: 998554587608-bf7td2slo768kopvdr30rs9tu7l3gbem.apps.googleusercontent.com"
echo "   Package Name: com.unveilix"
echo "   SHA-1: 5E:8F:16:06:2E:A3:CD:2C:4A:0D:54:78:76:BA:A6:F3:8C:AB:F6:25"
echo ""

echo "📋 Google Cloud Console Checklist:"
echo ""
echo "1. Go to: https://console.cloud.google.com/apis/credentials?project=acespire-485012"
echo ""
echo "2. You should see TWO OAuth 2.0 Client IDs:"
echo "   ✅ Type: Web application"
echo "      Client ID: 998554587608-bf7td2slo768kopvdr30rs9tu7l3gbem.apps.googleusercontent.com"
echo ""
echo "   ❓ Type: Android"
echo "      Package: com.unveilix"
echo "      SHA-1: 5E:8F:16:06:2E:A3:CD:2C:4A:0D:54:78:76:BA:A6:F3:8C:AB:F6:25"
echo "      👆 If you DON'T see this, CREATE IT NOW!"
echo ""

echo "3. Enable APIs:"
echo "   Go to: https://console.cloud.google.com/apis/library?project=acespire-485012"
echo "   Search and enable:"
echo "   - People API (or Google+ API)"
echo "   - Google Sign-In API"
echo ""

echo "4. After creating the Android OAuth client:"
echo "   - Wait 10 minutes"
echo "   - Then rebuild: npm run android"
echo ""

echo "=== Common Issues ==="
echo ""
echo "❌ DEVELOPER_ERROR = Missing Android OAuth client"
echo "   Solution: Create Android OAuth client with package name and SHA-1"
echo ""
echo "❌ SIGN_IN_REQUIRED = Wrong webClientId"
echo "   Solution: Use Web Client ID (not Android Client ID) in code"
echo ""
echo "❌ API not enabled = Missing People API"
echo "   Solution: Enable People API or Google+ API in Cloud Console"
echo ""

echo "=== Next Steps ==="
echo "1. Create Android OAuth client in Google Cloud Console (see above)"
echo "2. Wait 10 minutes"
echo "3. Run: npm run android"
echo "4. Test Google Sign-In"
echo ""
